### ISSUE TITLE
Multiply  _priceCents with quantity . 

### ISSUE THREAD

**Issue by neemydev** [OfficialFlutterButter/checkout_screen_ui#1]
you are not multiplying   _priceCents with item.qantity . if a item has quantity more than one , then it would be added to total amount . so please  just change one line in your checkout screen.  
  int _priceCents = 0;
    for (var item in priceItems) {
      _priceCents += item.totalPriceCents * item.quantity;
    }
do like this.

**Comment by OfficialFlutterButter** [comment]
added with the new PR #2 
Also a hand ful of new features
